### ISSUE TITLE
http cache-control different when image resize filters applied

### ISSUE THREAD

**Issue by patrickmichalina** [quix-labs/caddy-image-processor#12]
Is there a config that needs to be applied in order to apply the same cache control headers when a query param is applied?

**Comment by alancolant** [comment]
You'd like to pass a query parameter, for example: /image.png?w=400&cache_control=..., and transform the parameter into a header, correct?

In that case, you should be able to use an example configuration in Caddy with a header that retrieves the value from the query. Here’s how it could look:

If you are using file_server
```
localhost:80 {
    root /your/path/test-dataset
    
    @hasCacheControl query cache_control=*
    header @hasCacheControl Cache-Control {query.cache_control}

    file_server 
}
```

If you are using reverse_proxy
```
localhost:80 {    
    @hasCacheControl query cache_control=*
    reverse_proxy @hasCacheControl localhost:4000 {
        header_down Cache-Control {query.cache_control}
    }
    reverse_proxy localhost:4000
}
```

**Comment by alancolant** [comment]
Ok, it seems that Caddy generates the ETag header using modification time and file size.

Then, it defers ETag deletion if response doesn't match.

In our case, the ETag is deleted because the Content-Length differs from the initial value.

I need to reimplement a specific ETag generation mechanism to handle resized files.

This assumes that the ETag cannot be the same as the initial reverse-proxied value, but I can generate a specific ETag for each resized image

**Comment by alancolant** [comment]
I can generate an ETag, but the image processor doesn’t implement a caching mechanism to check if the newly resized image matches the client’s ETag.

As a result, the underlying caching mechanism cannot be accurate.

That said, I can generate an ETag, but I cannot handle a 304 Not Modified response when the content matches the client’s version without regenerating the image.

**Comment by alancolant** [comment]
I'll try to develop, by the end of the year, a caching system that takes into account the initial ETag returned by the proxy or file_server.

The goal is to cache a specific version based on the processing parameters, to avoid reprocessing the image for every request.

This would help save server resources by preventing unnecessary resizing.

However, it might take me some time to implement.

**Comment by alancolant** [comment]
Ok, I've implemented a custom mechanism to handle the ETag and If-None-Match headers according to the specific image processing for each image, if your initial proxy/file server returns an ETag specific to the file.

See https://github.com/quix-labs/caddy-image-processor/releases/tag/2.2.2

**Comment by patrickmichalina** [comment]
> Ok, I've implemented a custom mechanism to handle the ETag and If-None-Match headers according to the specific image processing for each image, if your initial proxy/file server returns an ETag specific to the file.
> 
> See https://github.com/quix-labs/caddy-image-processor/releases/tag/2.2.2
> 
> Regarding the cache-control, it seems more legitimate to reuse the one provided initially by the proxy/file server by default. Therefore, I suggest keeping the previous logic to overwrite it with a custom cache.
> 
> I don't see the point of globally bypassing the initial cache configured on the remote proxies.

Yeah I wasn't trying to override the cache response. I was just seeing two different results with and without query params. Thanks
